const departments = [
  'Agriculture',
  'ArtificialIntelligence',
  'Archaeology',
  'Art',
  'Astronomy',
  'SpaceExploration',
  'Chemistry',
  'ComputerScience',
  'CitiesofTheFuture',
  'CulturalStudies',
  'Economics',
  'Education',
  'Engineering',
  'EnvironmentalScience',
  'Genetics',
  'Geology',
  'History',
  'Law',
  'Linguistics',
  'Literature',
  'Materials',
  'Mathematics',
  'Mechanics',
  'MedicineandHealthSciences',
  'Meteorology',
  'Biology',
  'NanoTechnology',
  'Neuroscience',
  'Nutrition',
  'Oceanography',
  'Paleontology',
  'Pediatrics',
  'Philosophy',
  'Physics',
  'PoliticalScience',
  'Psychology',
  'MedicalImaging',
  'Robotics',
  'Sociology',
  'EarthSciences',
  'SportSciences',
  'Statistics',
  'Transportation',
  ];
  
  module.exports = departments;
  