const departments = [
    'Physics',
  'Chemistry',
  'Robotics',
  'Biology',
  'Earth Sciences',
  'Geology',
  'Meteorology',
  'Oceanography',
  'Astronomy and Space Science',
  'Environmental Science',
  'Mathematics',
  'Computer Science',
  'Statistics',
  'Psychology',
  'Sociology',
  'Anthropology',
  'Economics',
  'Political Science',
  'Engineering',
  'Medicine and Health Sciences',
  'Agricultural Sciences',
  'Environmental Engineering',
  'Computer Science',
  'History',
  'Philosophy',
  'Literature',
  'Linguistics',
  'Art History',
  'Cognitive Science',
  'Neuroscience',
  'Biophysics',
  'Biochemistry',
  'Data Science',
  'Artificial Intelligence'
  ];
  
  module.exports = departments;
  